[package]
name = "utils-wasm"
version = "0.3.3"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.1"

[lib]
crate-type = ["cdylib", "rlib"]