name: Build and NPM Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ['packages/core', 'packages/create-burner', 'packages/utils']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        scope: '@dojoengine'

    - name: Install dependencies
      run: |
        cd ${{ matrix.package }}
        bun install

    - name: Build
      run: |
        cd ${{ matrix.package }}
        bun run build

    - name: NPM Publish
      run: |
        cd ${{ matrix.package }}
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}